# appveyor.yml
---
environment:
  matrix:

  - PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5.0"
    PYTHON_ARCH: "64"
  
build: off

install:
- pip install . 
- pip install pytest

test_script:
- python3 pytest
