version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: mkdir test-reports && pip install tox
      - run:
          name: Run Test Suite
          command: tox
      - store_test_results:
                path: test-reports
      - store_artifacts:
                path: test-reports   