name: Python package

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up testing tools and environment for pylint
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run pylint test
        run: pylint --rcfile='./.pylintrc' magpylib

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8"] #, "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup testing tools and environment
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v2
      - name: Run code test coverage suite
        run: tox -e py
